name: santaikaan

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssasa code
        uses: actions/checkout@v4

      - name: sasa SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add sasa to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VPS_SSH_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: sasa to VPS
        run: |
          ssh -p "${{ secrets.VPS_SSH_PORT }}" "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" << 'EOF'
            set -e

            cd ${{ secrets.VPS_APP_DIR }}

            git fetch origin main
            git reset --hard origin/main

            docker compose pull || true
            docker compose up -d --build --remove-orphans

            docker system prune -f
          EOF
